name: Run Linter Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - release/*
    paths-ignore:
      - docs/*
      - "*.md"
  pull_request:

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - run: PYTHONPATH=$(pwd)/src/ pylint --fail-under 9 $(pwd)/src/

